name: CI

on:
  workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Build
      run: |
        npm install
        npm run-script build
      env:
        REACT_APP_SERVICE_ID: ${{ secrets.REACT_APP_SERVICE_ID }}
        REACT_APP_TEMPLATE_ID: ${{ secrets.REACT_APP_TEMPLATE_ID }}
        REACT_APP_PUBLIC_KEY: ${{ secrets.REACT_APP_PUBLIC_KEY }}

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:       
        BRANCH: gh-pages
        FOLDER: build
